DELETE from JOB_A_AP_PI_PERSONAL_DATA WHERE CREATE_USER = 'EXTERNAL';
DELETE from JOB_A_APPLICANT_CERTIFICATE WHERE CREATE_USER = 'EXTERNAL';
DELETE from JOB_A_APPLICANT WHERE CREATE_USER = 'EXTERNAL';

DELETE from SYS_M_USER_MAP_ADDRESS WHERE CREATE_USER = 'EXTERNAL';
DELETE from SYS_M_USER_MAP_PHONE WHERE CREATE_USER = 'EXTERNAL';

DELETE from SYS_M_ADDRESS WHERE CREATE_USER = 'EXTERNAL';
DELETE from SYS_M_PHONE WHERE CREATE_USER = 'EXTERNAL';
DELETE from JOB_M_USER_GENERAL_SETTING WHERE CREATE_USER = 'EXTERNAL';

DELETE from SYS_M_USER_MAP_ROLE WHERE CREATE_USER = 'EXTERNAL';
DELETE from JOB_M_USER_EMAIL WHERE CREATE_USER = 'EXTERNAL';
DELETE from SYS_M_USER_LANG WHERE CREATE_USER = 'EXTERNAL';

DELETE from SYS_M_USER WHERE CREATE_USER = 'EXTERNAL';