ALTER TABLE `SYS_M_USER`
DROP COLUMN `REF_ID`,
DROP INDEX `REF_ID`;


ALTER TABLE `SYS_M_PHONE`
DROP COLUMN `REF_ID`,
DROP COLUMN `ID_USER`,
DROP INDEX `REF_ID`,
DROP INDEX `ID_USER`;

ALTER TABLE `SYS_M_ADDRESS`
DROP COLUMN `REF_ID`,
DROP COLUMN `ID_USER`,
DROP INDEX `REF_ID`,
DROP INDEX `ID_USER`;