ALTER TABLE `SYS_M_USER`
ADD COLUMN `REF_ID`  bigint NULL AFTER `UPDATE_USER`,
ADD INDEX (`REF_ID`) ;


ALTER TABLE `SYS_M_PHONE`
ADD COLUMN `REF_ID`  bigint NULL AFTER `UPDATE_USER`,
ADD INDEX (`REF_ID`) ;

ALTER TABLE `SYS_M_PHONE`
ADD COLUMN `ID_USER`  bigint NULL AFTER `REF_ID`,
ADD INDEX (`ID_USER`) ;

ALTER TABLE `SYS_M_ADDRESS`
ADD COLUMN `ID_USER`  bigint NULL AFTER `UPDATE_USER`,
ADD INDEX (`ID_USER`) ;

ALTER TABLE `SYS_M_ADDRESS`
ADD COLUMN `REF_ID`  bigint NULL AFTER `ID_USER`,
ADD INDEX (`REF_ID`) ;